-- MySQL Script generated by MySQL Workbench
-- Tuesday 06 December 2016 05:22:13 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e-arc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e-arc` ;

-- -----------------------------------------------------
-- Schema e-arc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e-arc` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `e-arc` ;

-- -----------------------------------------------------
-- Table `e-arc`.`MI_DefaultTemplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-arc`.`MI_DefaultTemplate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-arc`.`MI_DefaultTemplate` (
  `TemplateId` INT NOT NULL AUTO_INCREMENT,
  `TemplateName` VARCHAR(100) NULL,
  `TemplateImage` TEXT NULL,
  `IsActive` BIT NULL DEFAULT 1,
  `TemplateConfig` JSON NULL,
  PRIMARY KEY (`TemplateId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `e-arc`.`AC_UserCustomTemplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-arc`.`AC_UserCustomTemplate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-arc`.`AC_UserCustomTemplate` (
  `TemplateId` INT NOT NULL AUTO_INCREMENT,
  `PWUserId` INT NULL,
  `TemplateConfig` JSON NULL,
  `IsDeleted` BIT NULL,
  `DefaultTemplateID` INT NULL,
  `CreateBy` INT NULL,
  `CreateDate` DATETIME NULL,
  `ModifyBy` INT NULL,
  `ModifyDate` DATETIME NULL,
  PRIMARY KEY (`TemplateId`),
  CONSTRAINT `DefaultTemplateID`
    FOREIGN KEY (`DefaultTemplateID`)
    REFERENCES `e-arc`.`MI_DefaultTemplate` (`TemplateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;

SHOW WARNINGS;
CREATE INDEX `DefaultTemplateID_idx` ON `e-arc`.`AC_UserCustomTemplate` (`DefaultTemplateID` ASC);

SHOW WARNINGS;
CREATE INDEX `UserId_index` ON `e-arc`.`AC_UserCustomTemplate` (`PWUserId` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `e-arc`.`MI_DefaultTemplate`
-- -----------------------------------------------------
START TRANSACTION;
USE `e-arc`;
INSERT INTO `e-arc`.`MI_DefaultTemplate` (`TemplateId`, `TemplateName`, `TemplateImage`, `IsActive`, `TemplateConfig`) VALUES (1, 'Sample1', NULL, 1, '{\"color\": \"#235435\"}');
INSERT INTO `e-arc`.`MI_DefaultTemplate` (`TemplateId`, `TemplateName`, `TemplateImage`, `IsActive`, `TemplateConfig`) VALUES (2, 'Sample2', NULL, 1, '{\"color\": \"#35435\"}');
INSERT INTO `e-arc`.`MI_DefaultTemplate` (`TemplateId`, `TemplateName`, `TemplateImage`, `IsActive`, `TemplateConfig`) VALUES (3, 'Sample3', NULL, 1, '{\"color\": \"#8B8B8B\"}');

COMMIT;

